proiect/aplicatie/urls.py
from django.urls import path

from aplicatie import views

app_name = 'transactions'

urlpatterns = [
    path('', views.TransactionsView.as_view(), name='transactions_list'),
    path('add_transaction/', views.CreateTransactionsView.as_view(), name='add'),
    path('incomes/', views.IncomesView.as_view(), name='incomes'),
    path('expenses/', views.ExpensesView.as_view(), name='expenses'),
    path('incomes_report/', views.IncomesReportView.as_view(), name='incomes_report'),
    # path('report/', views.ExpensesReportDef, name='report'),
    path('expenses_report/', views.ExpensesReportView.as_view(), name='expenses_report'),
    path('<int:pk>/update/', views.UpdateTransactionsView.as_view(), name='update'),
    path('<int:pk>/delete/', views.delete_transaction, name='delete'),
    path('<int:pk>/activate/', views.activate_transaction, name='activate')
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('transactions/', include('aplicatie.urls')),
    path('', include('django.contrib.auth.urls'), {'nextpage': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('userprofile/', include('userprofile.urls')),
]

proiect/aplicatie/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=300)
    active = models.BooleanField(default=True)

    # subcat = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    # subcategories = []

    # def __init__(self, name):
    #     self.name = name

    def __str__(self):
        return f'{self.name}'


class Subcategory(models.Model):
    name = models.CharField(max_length=300)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)
    models.BooleanField(default=True)

    # subcategories = []

    # Transactions
    # id = 1 subcategory_id = 1
    # id = 2 subcategory_id = 2
    #
    # Subcategory
    # id = 1 category_id = 1
    # id = 2 category_id = 3
    #
    # Category
    # id = 1 nume = cheltuieli_masina
    # id = 2 nume = cheltuieli_casa
    # id = 3 nume = cheltuieli_curs
    #

    def __str__(self):
        return f'{self.name}'


class Transactions(models.Model):
    date = models.DateTimeField(null=True)
    account = models.CharField(max_length=300)
    subcategory = models.ForeignKey(
        Subcategory,
        on_delete=models.CASCADE,
    )
    amount = models.FloatField()
    note = models.CharField(max_length=300)
    type = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.date} --> {self.amount}'


class Logs(models.Model):
    action_choices = (('created', 'created'),
                      ('updated', 'update'),
                      ('refresh', 'refresh'))
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True)
    action = models.CharField(max_length=10, choices=action_choices)
    url = models.CharField(max_length=100)

proiect/aplicatie/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.forms import forms
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse
from aplicatie.models import Transactions
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here. 'LoginRequiredMixin'?

class TransactionsView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Transactions
    template_name = 'aplicatie/transactions_index.html'
    permission_required = 'transactions.view_transactions'

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     data = super(TransactionsView, self).get_context_data(**kwargs)
    #     return data


class CreateTransactionsView(LoginRequiredMixin, CreateView):
    model = Transactions
    fields = ['date', 'account', 'amount', 'note', 'subcategory', 'type']
    template_name = 'aplicatie/transactions_form.html'

    def get_success_url(self):
        return reverse('transactions:transactions_list')

    # def get_form(self):
    #     """add date picker in forms"""
    #     form = super(CreateTransactionsView, self).get_form()
    #     form.fields['end_date'].widget = forms.DateInput(attrs={'type': 'date'})
    #     return form


class IncomesView(LoginRequiredMixin, ListView):
    model = Transactions
    template_name = 'aplicatie/incomes.html'


class ExpensesView(LoginRequiredMixin, ListView):
    model = Transactions
    template_name = 'aplicatie/expenses.html'


class IncomesReportView(LoginRequiredMixin, ListView):
    model = Transactions
    template_name = 'aplicatie/incomes_report.html'


class ExpensesReportView(LoginRequiredMixin, ListView):
    model = Transactions
    template_name = 'aplicatie/expenses_report.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['qs'] = Transactions.objects.all()
        return context


@login_required
def ExpensesReportDef(request):
    template_name = 'aplicatie/expenses_report.html'
    trans = Transactions.objects.all()

    context = {
        'trans': trans
    }
    print(context)
    render(request, 'aplicatie/expenses_report.html', context)


class UpdateTransactionsView(LoginRequiredMixin, UpdateView):
    model = Transactions
    fields = ['date', 'account', 'amount', 'note', 'subcategory', 'type']
    template_name = 'aplicatie/transactions_form.html'

    def get_success_url(self):
        return reverse('transactions:transactions_list')


@login_required
def delete_transaction(request, pk):
    Transactions.objects.filter(id=pk).update(active=False)
    return redirect('transactions:transactions_list')


@login_required
# @permission_required()
def activate_transaction(request, pk):
    Transactions.objects.filter(id=pk).update(active=True)
    return redirect('transactions:transactions_list')

proiect/templates/aplicatie/expenses.html
{% extends 'base.html' %}

{% block title %}
<p1>Aici vor fi afisate cheltuielile</p1>
<table class="table" style="margin-top: 10x">
    <thead>
        <tr>
            <th>Date</th>
            <th>Account</th>
            <th>Amount</th>
            <th>Note</th>
<!--            <th>Type</th>-->
        </tr>
    </thead>
    <tbody>
            {% for item in transactions_list %}
                <tr>
                    {% if not item.type and item.active %}
                        <td>{{ item.date }}</td>
                        <td>{{ item.account }}</td>
                        <td>{{ item.amount }}</td>
                        <td>{{ item.note }}</td>
                         <td>
                            <a class="btn btn-warning btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:update' item.id %}">Update</a>

                            <a class="btn btn-danger btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:delete' item.id %}">Delete</a>
                        </td>
<!--                        <td>-->
<!--                            <a class="btn btn-sm btn-success" href="{% url 'transactions:add' %}">Add transaction</a>-->
<!--                        </td>-->
                {% endif %}
                </tr>
            {% endfor %}
    </tbody>
</table>
{% endblock %}

proiect/templates/aplicatie/expenses_report.html
{% extends 'base.html' %}
{% block title %}
    <br>
    <p1>Aici vor fi afisate rapoarte privind cheltuielile</p1>
    <br>
    <div>
        <div>
          <canvas id="myChart"></canvas>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <script>
          const ctx = document.getElementById('myChart');

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: [{% for tran in context %}
                            {{ tran.date }}
                        {% endfor %}],
              datasets: [{
                label: '# of Votes',
                data: [12, 19, 3, 5, 2, 3],
                borderWidth: 1
              }]
            },
            options: {
              scales: {
                y: {
                  beginAtZero: true
                }
              }
            }
          });
        </script>

    </div>
<!--      const ctx = document.getElementById('myChart');-->

<!--      new Chart(ctx, {-->
<!--        type: 'bar',-->
<!--        data: {-->
<!--          labels: [-->
<!--                        {% for tran in transactions_list %}-->
<!--                            {{ tran.date }}-->
<!--                        {% endfor %}-->
<!--                    ],-->
<!--          datasets: [{-->
<!--            label: '#',-->
<!--            data: [-->
<!--                        {% for tran in trans %}-->
<!--                            {{tran.amount}}-->
<!--                        {% endfor %}-->
<!--                    ],-->
<!--            borderWidth: 1-->
<!--          }]-->
<!--        },-->
<!--        options: {-->
<!--          scales: {-->
<!--            y: {-->
<!--              beginAtZero: true-->
<!--            }-->
<!--          }-->
<!--        }-->
<!--      });-->
    </script>



{% endblock %}

proiect/templates/aplicatie/incomes.html
{% extends 'base.html' %}
{% block title %}
<p1>Aici vor fi afisate veniturile</p1>
<table class="table" style="margin-top: 10x">
    <thead>
        <tr>
            <th>Date</th>
            <th>Account</th>
            <th>Amount</th>
            <th>Note</th>
<!--            <th>Type</th>-->
        </tr>
    </thead>
    <tbody>
            {% for item in transactions_list %}
                <tr>
                    {% if item.type and item.active %}
                        <td>{{ item.date }}</td>
                        <td>{{ item.account }}</td>
                        <td>{{ item.amount }}</td>
                        <td>{{ item.note }}</td>
                        <td>
                            <a class="btn btn-warning btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:update' item.id %}">Update</a>

                            <a class="btn btn-danger btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:delete' item.id %}">Delete</a>
                        </td>
<!--                        <td>-->
<!--                            <a class="btn btn-sm btn-success" href="{% url 'transactions:add' %}">Add transaction</a>-->
<!--                        </td>-->
                    {% endif %}
                </tr>
            {% endfor %}
    </tbody>
</table>
{% endblock %}

proiect/templates/aplicatie/incomes_report.html
{% extends 'base.html' %}
{% block title %}
<p1>Aici vor fi afisate rapoarte privind veniturile</p1>
{% endblock %}

proiect/templates/aplicatie/sidebar.html
{% load static %}
    <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
                    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
                        <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
                        </div>
                        {% if request.user.is_authenticated %}
                        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="btn btn-success btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:add' %}">Add Transaction</a>
                                    <a class="btn btn-primary btn-sm"
                                       style="margin-left: 5px"
                                       aria-current="page"
                                       href="{% url 'transactions:transactions_list' %}">
<!--                                        <svg class="bi"><use xlink:href="#house-fill"/></svg>-->
                                        All Transactions
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'transactions:expenses' %}">
<!--                                        <svg class="bi"><use xlink:href="#file-earmark"/></svg>-->
                                        Expenses
                                    </a>
                                </li>
                                <li class="nav-item">
<!--                                    ?category={{categorY_id}}-->
                                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'transactions:incomes' %}">
<!--                                        <svg class="bi"><use xlink:href="#cart"/></svg>-->
                                        Incomes
                                    </a>
                                </li>

                            </ul>

                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
                                <span>Reports</span>
                                <a class="link-secondary" href="#" aria-label="Add a new report">
<!--                                    <svg class="bi"><use xlink:href="#plus-circle"/></svg>-->
                                </a>
                            </h6>
                            <ul class="nav flex-column mb-auto">
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'transactions:expenses_report' %}">
<!--                                        <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>-->
                                       Expenses Report
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'transactions:incomes_report' %}">
<!--                                        <svg class="bi"><use xlink:href="#file-earmark-text"/></svg>-->
                                        Incomes Report
                                    </a>
                                </li>

                            </ul>

                            <hr class="my-3">

                            <ul class="nav flex-column mb-auto">
<!--                                <li class="nav-item">-->
<!--                                    <a class="nav-link d-flex align-items-center gap-2" href="#">-->
<!--&lt;!&ndash;                                        <svg class="bi"><use xlink:href="#gear-wide-connected"/></svg>&ndash;&gt;-->
<!--                                        Settings-->
<!--                                    </a>-->
<!--                                </li>-->
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center gap-2" href="#">
<!--                                        <svg class="bi"><use xlink:href="#door-closed"/></svg>-->
                                        <form action="{% url 'logout' %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-md btn-danger" type="submit">Sign out</button>
                                        </form>

                                    </a>
                                </li>
                            </ul>
                        </div>
                        {% endif %}
                    </div>
                </div>

proiect/templates/aplicatie/transactions_form.html
{% extends 'base.html' %}
{% block title %}
    <br>
    <select id="test" name="form_select" onchange="showDiv(this)">
        {% if field.label == 'subcategory' %}
            {{ field.label }} {{ field }}
        {% endif %}
    </select>
    <div id="hidden_div" style="display:none;">Hello hidden content</div>
    <br>
    <script type="text/javascript">
    function showDiv(select){
       if(select.value==1){
        document.getElementById('hidden_div').style.display = "block";
       } else{
        document.getElementById('hidden_div').style.display = "none";
       }
    }
    </script>

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
                {{ field.label }} {{ field }}
            <span class="text-danger small" >{{ field.errors }}</span>
        {% endfor %}
        <button type="submit" class="btn btn-md btn-success">Salveaza</button>
    </form>
{% endblock %}

proiect/templates/aplicatie/transactions_index.html
{% extends 'base.html' %}
{% block title %}
    <table class="table" style="margin-top: 10x">
        <thead>
            <tr>
                <th>Date</th>
                <th>Account</th>
                <th>Amount</th>
                <th>Note</th>
                <th>Type</th>
                <th>Active</th>
            </tr>
        </thead>
        <tbody>
            {% for item in transactions_list %}
                <tr>
                    <td>{{ item.date }}</td>
                    <td>{{ item.account }}</td>
                    <td>{{ item.amount }}</td>
                    <td>{{ item.note }}</td>
<!--                    <td>{{ item.type }}</td>-->
                    <td>
                            <a class="btn btn-warning btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:update' item.id %}">Update</a>
                            {% if item.active %}
                                <a class="btn btn-danger btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:delete' item.id %}">Delete</a>
                            {% else %}
                                <a class="btn btn-info btn-sm"  style="margin-left: 10px"
                                       href="{% url 'transactions:activate' item.id %}">Activate</a>
                            {% endif %}
                    </td>
                    <td>{{ item.active }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}